---
version: '2'

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - "2191:2191" 
      - "2291:2291"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2191
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_JMX_HOSTNAME: zookeeper1
      ZOOKEEPER_SERVERS: 0.0.0.0:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
      ZOOKEEPER_LOG4J_LOGGERS: kafka=ERROR,
        kafka.controller=ERROR,
        kafka.network.RequestChannel$=ERROR,
        kafka.producer.async.DefaultEventHandler=DEBUG,
        kafka.request.logger=WARN,
        kafka.log.LogCleaner=ERROR,
        state.change.logger=ERROR,
        kafka.authorizer.logger=ERROR

  broker:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9192:9192"
      - "9101:9101"
    restart: "on-failure"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2191'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://broker1:9092,PLAINTEXT_EXTERNAL://172.20.48.213:9192
      # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8083
      # CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1:29092
      # CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      # CONFLUENT_METRICS_ENABLE: 'true'
      # CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_LOG4J_LOGGERS: kafka=ERROR,
        kafka.controller=ERROR,
        kafka.network.RequestChannel$=ERROR,
        kafka.producer.async.DefaultEventHandler=DEBUG,
        kafka.request.logger=WARN,
        kafka.log.LogCleaner=ERROR,
        state.change.logger=ERROR,
        kafka.authorizer.logger=ERROR  